### ISSUE TITLE
Integration with pybtex?

### ISSUE THREAD

**Issue by cpitclaudel** [dschwilk/bibstuff#3]
Hi there,

Is there a way to use bibstuff as a pybtex backend for to generate a list of reStructuredText references from a `bib` file?  Or can bibstuff only be used on its own?

Thanks a lot!

**Comment by dschwilk** [comment]
My impression is that there are better tools that now supersede all of bibstuff so I have not done any integration or work on it and it is essentially retired.

There was a suggestion a long time ago to use pybtex as a backend for the restructured text parts of bibstuff.  See https://github.com/matthew-brett/bibstuff/issues/11#issuecomment-43185002

**Comment by cpitclaudel** [comment]
Are there better tools?  With phinx, yes, but with plain docutils I'm not sure.

**Comment by dschwilk** [comment]
Good point. I'm not sure either. I'll let Alan answer as he has been the one keeping this alive and working on bibstuff since 2014.

**Comment by alan-isaac** [comment]
I don't know of a good replacement for working with vanilla docutils.

**Comment by alan-isaac** [comment]
Hi @cpitclaudel 
I don't understand the workflow you envisage. Can you please elaborate? It seems you are fundamentally asking if you can convert *all* entries of a given .bib file to reST citations instead just the entries in a give reST file. How wd this need arise?

**Comment by cpitclaudel** [comment]
>  Can you please elaborate?

Yes of course.  I'm used to working with pybtex, and they have nice command-line tools; in particular you can take a bib file and export it as a list of references.

It doesn't currently have a rst backend, and I think the functionality in bibstuff is exactly suited for that purpose.

The workflow looks like this: you have a file with a bunch of citations; for LaTeX you want to use `\cite` but for HTML you want to format as reST.  Then you need to generate a list of references.  So you could take a bibtex file, convert it to a list of reST references, and `.. include` it.

**Comment by alan-isaac** [comment]
What is the format of "a file with a bunch of citations"? Are you actually starting with pybtex.richtext? Or is it that you start with reST but want more control over the inline citation format when you export to HTML?

**Comment by cpitclaudel** [comment]
> What is the format of "a file with a bunch of citations"?

I was thinking reST.  Something like this:

```rst
Previous work includes X [Abc2018]_, Y [Def1954]_, and Z [Uvw1967]
```

Then exported to LaTeX this becomes regular `\cite{}` commands, but for exporting to HTML I'd like to create a reST file like this:

```rst
.. [Abc2018] Abc. *The X system*. Journal of xyzs, 2018.
.. [Def1954] Def. *The Y system*. Yzt symposium, 1954.
```

> This might seem off-topic, but are you aware that reST documents can include raw HTML?

I am aware :)

**Comment by alan-isaac** [comment]
It sounds like you are asking for the [bib4txt](https://github.com/dschwilk/bibstuff/blob/master/scripts/bib4txt.py) script?

**Comment by cpitclaudel** [comment]
Thanks, I might have misunderstood the purpose of that script.  I will look into it.

**Comment by cpitclaudel** [comment]
Thanks for the pointer.  I tested it.  I had trouble testing it because the help is broken, so I opened a PR for that.  It does almost what I need, except I'd prefer for it to format the whole list, not just the entries that are in fact cited, but I can patch this locally.

**Comment by cpitclaudel** [comment]
(Sorry for the noise, btw; I had misunderstood the purpose of the script)
